# Generated by Django 5.1.5 on 2025-02-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
    ]
