# Generated by Django 5.1.5 on 2025-02-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('slug',), 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
